# .github/workflows/github-pages.yml
name: GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify a compatible Ruby version

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
